[package]
name = "monocypher-sys"
version = "2.0.5"
authors = ["js@ciphron.de"]
description = "Bindgen generated bindings to the monocypher C library"
homepage = "https://monocypher.org"
keywords = ["api-bindings", "cryptography"]
license = "ISC"

[build-dependencies]
bindgen = "0.46"
